# Generated by Django 3.1.7 on 2023-12-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='text',
        ),
    ]
